apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-2-db
spec:
  selector:
    matchLabels:
      type: db
      service: go-demo-2
  template:
    metadata:
      labels:
        type: db
        service: go-demo-2
        vendor: MongoLabs
    spec:
      containers:
      - name: db
        image: mongo:3.3
        ports:
        - containerPort: 28017

---

apiVersion: v1
kind: Service
metadata:
  name: go-demo-2-db
spec:
  ports:
  - port: 27017
  selector:
    type: db
    service: go-demo-2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-2-api-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      type: api
      service: go-demo-2
      color: blue
  template:
    metadata:
      labels:
        type: api
        service: go-demo-2
        color: blue
        language: go
    spec:
      containers:
      - name: api
        image: vfarcic/go-demo-2
        env:
        - name: DB
          value: go-demo-2-db
        readinessProbe:
          httpGet:
            path: /demo/hello
            port: 8080
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /demo/hello
            port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-2-api-green
spec:
  replicas: 0
  selector:
    matchLabels:
      type: api
      service: go-demo-2
      color: green
  template:
    metadata:
      labels:
        type: api
        service: go-demo-2
        color: green
        language: go
    spec:
      containers:
      - name: api
        image: vfarcic/go-demo-2
        env:
        - name: DB
          value: go-demo-2-db
        readinessProbe:
          httpGet:
            path: /demo/hello
            port: 8080
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /demo/hello
            port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: go-demo-2-api
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    type: api
    service: go-demo-2
    color: blue

---

apiVersion: v1
kind: Service
metadata:
  name: go-demo-2-api-test
spec:
  ports:
  - port: 18080
  selector:
    type: api
    service: go-demo-2
    color: green
