jenkins:
  master:
    tag: "2.204.1-alpine"
    cpu: "500m"
    memory: "500Mi"
    serviceType: ClusterIP
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    installPlugins:
    - durable-task:1.33
    - workflow-durable-task-step:2.35
    - blueocean:1.21.0
    - credentials:2.3.0
    - ec2:1.47
    - git:4.0.0
    - git-client:3.0.0
    - github:1.29.5
    - kubernetes:1.22.3
    - pipeline-utility-steps:2.3.1
    - pipeline-model-definition:1.5.0
    - slack:2.35
    - thinBackup:1.9
    - workflow-aggregator:2.6
    - ssh-slaves:1.31.0
    - ssh-agent:1.17
    - jdk-tool:1.4
    - command-launcher:1.4
    - github-oauth:0.33
    - google-compute-engine:4.2.0
    - pegdown-formatter:1.3
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/proxy-body-size: 50m
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        ingress.kubernetes.io/ssl-redirect: "false"
        ingress.kubernetes.io/proxy-body-size: 50m
        ingress.kubernetes.io/proxy-request-buffering: "off"
    hostName: jenkins.acme.com
    customConfigMap: true
    credentialsXmlSecret: jenkins-credentials
    secretsFilesSecret: jenkins-secrets
    DockerVM: false
    # DockerAMI: 
    # GProject:
    # GAuthFile:
    # GlobalLibraries: true
  rbac:
    create: true
